INSERT INTO REPORT (TEACHER, ROOM, PROBLEM_DESCRIPTION, STATUS, SUBMISSION_DATE, START_DATE)
VALUES ('Jan Kowalski', '101', 'Projektor nie działa.', 'Zakończone', '2024-10-01 08:30:00', NULL);

INSERT INTO REPORT (TEACHER, ROOM, PROBLEM_DESCRIPTION, STATUS, SUBMISSION_DATE, START_DATE)
VALUES ('Anna Nowak', '202', 'Komputer nie uruchamia się.', 'Nowe', '2024-10-02 09:15:00', NULL);

INSERT INTO REPORT (TEACHER, ROOM, PROBLEM_DESCRIPTION, STATUS, SUBMISSION_DATE, START_DATE)
VALUES ('Piotr Zieliński', '103', 'Brak internetu.', 'Nowe', '2024-10-03 10:45:00', NULL);

-- Dodatkowe 3 nowe zgłoszenia
INSERT INTO REPORT (TEACHER, ROOM, PROBLEM_DESCRIPTION, STATUS, SUBMISSION_DATE, START_DATE)
VALUES ('Maria Wiśniewska', '04', 'Zacinająca się tablica interaktywna.', 'Nowe', '2024-10-04 11:00:00', NULL);

INSERT INTO REPORT (TEACHER, ROOM, PROBLEM_DESCRIPTION, STATUS, SUBMISSION_DATE, START_DATE)
VALUES ('Tomasz Lewandowski', '26', 'Nie działa oświetlenie.', 'Nowe', '2024-10-05 14:30:00', NULL);

INSERT INTO REPORT (TEACHER, ROOM, PROBLEM_DESCRIPTION, STATUS, SUBMISSION_DATE, START_DATE)
VALUES ('Ewa Kaczmarek', '60W', 'Klimatyzacja nie działa.', 'Nowe', '2024-10-06 16:00:00', NULL);
